"use client";
import { FormEvent, useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
type Review = { slug: string; category: string; title: string; cover: string; detailImage: string; score: number; text: string };
const empty: Review = { slug: "", category: "games", title: "", cover: "", detailImage: "", score: 0, text: "" };
export default function AdminReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [form, setForm] = useState<Review>(empty); const [message, setMessage] = useState("");
  const load = async () => { const res = await fetch("/api/reviews"); if (res.ok) setReviews(await res.json()); }; useEffect(() => { load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); const res = await fetch("/api/reviews", { method: form.slug ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setMessage(res.ok ? "保存成功" : "保存失败"); if (res.ok) { setForm(empty); load(); } };
  return <div className="min-h-screen bg-white flex flex-col"><Navbar adminBadge /><main className="flex-1 px-4 md:px-8 lg:px-12 py-10 md:py-14 w-full max-w-5xl mx-auto"><div className="flex items-center justify-between mb-8"><div><p className="text-xs tracking-widest uppercase text-neutral-500 mb-2">Admin</p><h1 className="text-2xl md:text-3xl font-semibold text-neutral-900">Reviews</h1></div><button type="button" onClick={() => setForm(empty)} className="border border-neutral-900 px-4 py-2 text-xs tracking-widest uppercase">New Review</button></div><form onSubmit={submit} className="space-y-4 border border-neutral-200 p-5 mb-10"><div className="grid md:grid-cols-2 gap-4"><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="评价标题" className="border px-3 py-2 text-sm" required /><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="border px-3 py-2 text-sm"><option value="games">Games</option><option value="movies">Movies</option><option value="books">Books</option></select><input value={form.score} min="0" max="10" type="number" onChange={(e) => setForm({ ...form, score: Number(e.target.value) })} placeholder="评分 0-10" className="border px-3 py-2 text-sm" /><input value={form.cover} onChange={(e) => setForm({ ...form, cover: e.target.value })} placeholder="封面相对路径，如 slay-the-spire/cover.jpg" className="border px-3 py-2 text-sm" required /><input value={form.detailImage} onChange={(e) => setForm({ ...form, detailImage: e.target.value })} placeholder="详情图相对路径，如 slay-the-spire/detail.jpg" className="border px-3 py-2 text-sm" required /></div><textarea value={form.text} onChange={(e) => setForm({ ...form, text: e.target.value })} placeholder="短评内容" className="w-full border px-3 py-2 text-sm min-h-48" required /><button className="bg-neutral-900 text-white px-5 py-2 text-xs tracking-widest uppercase">保存</button>{message && <span className="ml-3 text-xs text-neutral-500">{message}</span>}</form><div className="space-y-3">{reviews.map((review) => <button type="button" key={review.slug} onClick={() => setForm(review)} className="w-full text-left border border-neutral-200 p-4 hover:border-neutral-900"><span className="text-sm text-neutral-900">{review.title}</span><span className="ml-4 text-xs text-neutral-500">{review.category} / {review.score}</span></button>)}</div></main></div>;
}
